[target.wasm32-unknown-unknown]
runner = 'wasm-bindgen-test-runner'

[alias]
binstall = ["bin", "cargo-binstall"]
dylint = ["bin", "cargo-dylint"]
llvm-cov = ["bin", "cargo-llvm-cov"]
nextest = ["bin", "cargo-nextest"]
semver-checks = ["bin", "cargo-semver-checks"]

test_wallet_standard = [
	"nextest",
	"run",
	"--package",
	"wallet_standard",
	"-F",
	"solana",
]

coverage_wallet_standard = [
	"llvm-cov",
	"--no-report",
	"--package",
	"wallet_standard",
	"-F",
	"solana",
]

coverage_codecov_report = [
	"llvm-cov",
	"report",
	"--doctests",
	"--codecov",
	"--output-path",
	"codecov.json",
]
