name: "ci"

permissions:
  pull-requests: write
  contents: write
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    timeout-minutes: 60
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: lint clippy
        run: lint:clippy
        shell: devenv shell -- bash -e {0}

      - name: lint formatting
        run: lint:format
        shell: devenv shell -- bash -e {0}

  docs:
    timeout-minutes: 60
    runs-on: blacksmith-2vcpu-ubuntu-2404
    env:
      RUSTUP_TOOLCHAIN: "nightly"
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: build docs
        run: build:docs
        shell: devenv shell -- bash -e {0}

  test:
    timeout-minutes: 60
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: test `wallet_standard`
        run:
          sudo prlimit --pid $$ --nofile=1000000:1000000
          cargo test_wallet_standard
        shell: devenv shell -- bash -e {0}

  coverage:
    timeout-minutes: 60
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: coverage `wallet_standard`
        run: cargo coverage_wallet_standard
        shell: devenv shell -- bash -e {0}

      - name: coverage `codecov_report`
        run: cargo coverage_codecov_report
        shell: devenv shell -- bash -e {0}

      - name: upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: codecov.json
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    timeout-minutes: 60
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        run: cargo build --locked
        shell: devenv shell -- bash -e {0}

      - name: build all features
        run: build:all
        shell: devenv shell -- bash -e {0}
