name: "ci"

permissions:
  pull-requests: write
  contents: write
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    timeout-minutes: 60
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nix-cache: /tmp/nixcache

      - uses: clechasseur/rs-clippy-check@v3
        with:
          args: --all-features

      - name: install nightly rustfmt
        run: rustup toolchain install nightly --component rustfmt
        shell: bash

      - name: lint formatting
        run: lint:format
        shell: bash

  docs:
    timeout-minutes: 60
    runs-on: blacksmith-2vcpu-ubuntu-2404
    env:
      RUSTUP_TOOLCHAIN: "nightly"
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nix-cache: /tmp/nixcache

      - name: build docs
        run: build:docs
        shell: bash

  test:
    timeout-minutes: 60
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h

      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nix-cache: /tmp/nixcache

      - name: test `wallet_standard`
        run: cargo test_wallet_standard
        shell: bash

  coverage:
    timeout-minutes: 60
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h

      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nix-cache: /tmp/nixcache

      - name: coverage `wallet_standard`
        run: cargo coverage_wallet_standard
        shell: bash

      - name: coverage `codecov_report`
        run: cargo coverage_codecov_report
        shell: bash

      - name: upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: codecov.json
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    timeout-minutes: 60
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nix-cache: /tmp/nixcache

      - name: build
        run: cargo build --locked
        shell: bash

      - name: build all features
        run: build:all
        shell: bash
